
FROM maven:3.8.3-openjdk-17 AS BUILD
WORKDIR /app
COPY pom.xml .
COPY src src
RUN mvn package -q -Dmaven.test.skip=true

FROM openjdk:17-jdk-slim
WORKDIR /app
EXPOSE 8081
COPY --from=build /app/target/green-blue-test-0.0.1-SNAPSHOT.jar /app


CMD ["java", "-Dspring.profiles.active=prod", "-jar", "green-blue-test-0.0.1-SNAPSHOT.jar", "--server.port=9081"]